Fix docs after split from bazel_tools
bazelbuild/rules_java pull request #115
Opened 2023-06-09 08:42 UTC by fmeum

The `*_java_repository` macros no longer register toolchains.

2023-06-09 08:42 UTC, fmeum commented
CC @meteorcloudy

2023-06-09 08:42 UTC, fmeum commented
Note that I am using `:all` in preparation for https://github.com/bazelbuild/rules_java/pull/114.

2023-06-09 08:53 UTC, meteorcloudy approved these changes

2023-07-05 10:11 UTC, hvadehra requested changes

2023-07-05 10:11 UTC, hvadehra commented on toolchains/local_java_repository.bzl
> +    `<name>` is the value of the `name` parameter.
nit: also update L15 in the file's docstring?

2023-07-05 10:11 UTC, hvadehra commented on toolchains/remote_java_repository.bzl
> +    `<name>` is the value of the `name` parameter.
nit: also update L17 in the file's docstring?

2023-07-05 13:32 UTC, hvadehra approved these changes

2023-07-17 14:47 UTC, meteorcloudy approved these changes
Can we import this PR now?

2023-07-28 07:17 UTC, fmeum commented
@hvadehra Friendly ping

2023-07-28 07:22 UTC, hvadehra commented
I thought I'd already approved, and I don't see any new changes?

2023-07-28 07:25 UTC, hvadehra commented
Ah, I guess I should approve internally.

2023-07-28 07:27 UTC, merged