stardoc: allow rules_java to be used with stardoc
bazelbuild/rules_java pull request #51
Opened 2022-03-14 11:53 UTC by manuelnaranjo

Without this bzl_library definition users of rules_java get into
weird state when generating docs with stardoc

2022-03-16 11:36 UTC, comius approved these changes

2022-03-23 06:58 UTC, comius commented
Please rebase.

2022-03-23 06:58 UTC, comius requested changes
Please rebase.

2022-03-23 07:06 UTC, manuelnaranjo commented
> Please rebase.
After rebasing the pipeline has some failures, I'll check what changed and update the PR

2022-03-24 10:10 UTC, merged